In [1]:
import sys
sys.path.append('../wec-grid-code') # 
import wec_grid_class as wg
import sqlite3
import pandas as pd

    Sets PSSE environment to latest minor version among installed versions of PSSE 35.
    Use psse35.set_minor(n) to set PSSE35 minor version (n) to use.
        Example, for PSSE 35.0.x, use this as: psse35.set_minor(0)

In [ ]:
# Read in case file 
case14 = r"../input_files/RTS96DYN/IEEE_24_bus.raw"

In [ ]:
# initalize WEC GRID Object
pf = wg.Wec_grid(case14,"fnsl",3)

In [4]:
pf.dataframe

,BUS_ID,Bus,BASE,PU,ANGLED,Type,P Gen,Q Gen,P Load,Q Load,P,Q
0,1,BUS 1,138.0,1.000000,0.000000,3,35.930069,180.488586,NaN,NaN,35.930069,180.488586
1,2,BUS 2,138.0,0.997822,0.010373,2,67.000000,0.000000,97.0,20.000000,-30.000000,-20.000000
2,3,BUS 3,138.0,0.863703,10.755864,1,NaN,NaN,90.0,19.000000,-90.000000,-19.000000
3,4,BUS 4,138.0,0.887014,-0.415208,1,NaN,NaN,74.0,15.000001,-74.000000,-15.000001
4,5,BUS 5,138.0,0.927217,-0.229420,1,NaN,NaN,71.0,14.000000,-71.000000,-14.000000
5,6,BUS 6,138.0,0.907952,0.391817,1,NaN,NaN,68.0,14.000000,-68.000000,-14.000000
6,7,BUS 7,138.0,0.796234,-0.580059,2,64.000000,0.000000,62.0,13.000000,2.000000,-13.000000
7,8,BUS 8,230.0,0.805368,-0.868408,1,NaN,NaN,85.0,18.000000,-85.000000,-18.000000
8,9,BUS 9,138.0,0.834940,4.989085,1,NaN,NaN,175.0,36.000000,-175.000000,-36.000000
9,10,BUS 10,138.0,0.881702,3.723669,1,NaN,NaN,100.0,23.000000,-100.000000,-23.000000
10,11,BUS 11,230.0,0.836073,12.640563,1,NaN,NaN,NaN,NaN,NaN,NaN
11,12,BUS 12,230.0,0.839763,11.783456,1,NaN,NaN,NaN,NaN,NaN,NaN
12,13,BUS 13,230.0,0.836927,15.450583,2,200.000000,0.000000,130.0,27.000002,70.000000,-27.000002
13,14,BUS 14,230.0,0.836423,18.757851,2,0.000000,0.000000,92.0,20.000000,-92.000000,-20.000000
14,15,BUS 15,230.0,0.885209,33.212997,2,274.000000,0.000000,158.0,32.000000,116.000000,-32.000000
15,16,BUS 16,230.0,0.862146,27.084261,2,245.000000,0.000000,100.0,20.000000,145.000000,-20.000000
16,17,BUS 17,230.0,0.895736,32.061146,1,NaN,NaN,NaN,NaN,NaN,NaN
17,18,BUS 18,230.0,0.901057,33.899288,2,144.000000,0.000000,162.0,34.000000,-18.000000,-34.000000
18,19,BUS 19,230.0,0.851835,23.804094,1,NaN,NaN,90.0,18.000000,-90.000000,-18.000000
19,20,BUS 20,230.0,0.849352,22.331301,1,NaN,NaN,65.0,13.000000,-65.000000,-13.000000
20,21,BUS 21,230.0,0.911253,35.657959,2,294.000000,0.000000,NaN,NaN,294.000000,0.000000
21,22,BUS 22,230.0,1.000000,37.502068,2,150.000000,199.455856,NaN,NaN,150.000000,199.455856
22,23,BUS 23,230.0,0.849713,22.079517,2,200.000000,0.000000,NaN,NaN,200.000000,0.000000
23,24,BUS 24,230.0,0.854969,24.813110,1,NaN,NaN,NaN,NaN,NaN,NaN