In [156]:
net = pp.networks.case39()

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}

In [162]:
type(net.line.from_bus[0])

numpy.uint32

In [1]:
import pandapower as pp
import pandas as pd
import itertools

# Pandapower N-2 anaylsis code


def run_power_flow(net):
    pp.runpp(net)
    return net.res_bus, net.res_line


def get_line_buses(net, line_index):
    # Fetches the from_bus and to_bus of a line
    from_bus = net.line.at[line_index, "from_bus"] + 1
    to_bus = net.line.at[line_index, "to_bus"] + 1
    return (from_bus, to_bus)


def n_3_analysis(net):
    original_line_status = net.line.in_service.copy()
    contingency_results = []

    # Generate all combinations of three lines
    line_combinations = itertools.combinations(net.line.index, 3)

    for line1, line2, line3 in line_combinations:
        # Fetch bus information for the lines
        line1_buses = get_line_buses(net, line1)
        line2_buses = get_line_buses(net, line2)
        line3_buses = get_line_buses(net, line3)

        # Disconnect lines
        net.line.in_service.at[line1] = False
        net.line.in_service.at[line2] = False
        net.line.in_service.at[line3] = False

        # Run power flow
        try:
            pp.runpp(net)
            # Check if power flow converged
            converged = net["converged"]
            bus_voltages = net.res_bus.vm_pu.tolist()
            line_loadings = net.res_line.loading_percent.tolist()
            contingency_results.append(
                (
                    line1_buses,
                    line2_buses,
                    line3_buses,
                    converged,
                    bus_voltages,
                    line_loadings,
                )
            )
        except pp.LoadflowNotConverged:
            # Handle cases where power flow does not converge
            contingency_results.append(
                (line1_buses, line2_buses, line3_buses, False, [], [])
            )

        # Restore line status
        net.line.in_service.at[line1] = True
        net.line.in_service.at[line2] = True
        net.line.in_service.at[line3] = True

    return pd.DataFrame(
        contingency_results,
        columns=[
            "Line 1",
            "Line 2",
            "Line 3",
            "Converged",
            "Bus Voltages",
            "Line Loadings",
        ],
    )


def n_2_analysis(net):
    original_line_status = net.line.in_service.copy()
    contingency_results = []

    # Generate all combinations of two lines
    line_combinations = itertools.combinations(net.line.index, 2)

    for line1, line2 in line_combinations:
        # Fetch bus information for the lines
        line1_buses = get_line_buses(net, line1)
        line2_buses = get_line_buses(net, line2)

        # Disconnect lines
        net.line.in_service.at[line1] = False
        net.line.in_service.at[line2] = False

        # Run power flow
        try:
            pp.runpp(net)
            # Check if power flow converged
            converged = net["converged"]
            bus_voltages = net.res_bus.vm_pu.tolist()
            line_loadings = net.res_line.loading_percent.tolist()
            contingency_results.append(
                (line1_buses, line2_buses, converged, bus_voltages, line_loadings)
            )
        except pp.LoadflowNotConverged:
            # Handle cases where power flow does not converge
            contingency_results.append((line1_buses, line2_buses, False, [], []))

        # Restore line status
        net.line.in_service.at[line1] = True
        net.line.in_service.at[line2] = True

    return pd.DataFrame(
        contingency_results,
        columns=["Line 1", "Line 2", "Converged", "Bus Voltages", "Line Loadings"],
    )


# Create and setup network

net = pp.networks.case39()

# Run initial power flow
initial_bus_res, initial_line_res = run_power_flow(net)

initial_line_res

# Perform N-2 analysis
contingency_results = n_3_analysis(net)
print("\nN-2 Contingency Analysis Results:")
contingency_results

AttributeError: module 'pandapower' has no attribute 'networks'

In [155]:
contingency_results.loc[contingency_results["Converged"] == False]

       Line 1    Line 2  Converged  Slack Bus Voltage
0      (0, 1)   (0, 38)       True                NaN
1      (0, 1)    (1, 2)       True                NaN
2      (0, 1)   (1, 24)       True                NaN
3      (0, 1)    (2, 3)       True                NaN
4      (0, 1)   (2, 17)       True                NaN
..        ...       ...        ...                ...
590  (25, 26)  (25, 28)       True                NaN
591  (25, 26)  (27, 28)       True                NaN
592  (25, 27)  (25, 28)       True                NaN
593  (25, 27)  (27, 28)       True                NaN
594  (25, 28)  (27, 28)       True                NaN

[595 rows x 4 columns]

In [154]:
contingency_results.to_csv("contingency_results.csv", index=False)

In [5]:
# pyPSA n-2
# Standard Libraries
import os
import sys
from datetime import datetime, timezone, timedelta

# 3rd Party Libraries
import pypsa
import pandas as pd
import cmath
import matlab.engine
import pypsa
import pypower.api as pypower
import pandapower
import itertools
from tqdm import tqdm
import matplotlib.pyplot as plt

In [6]:
case_file = "../models/grid_models/IEEE_39_bus.RAW"

eng = matlab.engine.start_matlab()
eng.workspace["case_path"] = case_file
eng.eval("mpc = psse2mpc(case_path)", nargout=0)
eng.eval("savecase('here.mat',mpc,1.0)", nargout=0)

# Load the MATPOWER case file from a .mat file
ppc = pypower.loadcase("./here.mat")

# Convert Pypower network to PyPSA network
pypsa_network = pypsa.Network()
pypsa_network.import_from_pypower_ppc(ppc, overwrite_zero_s_nom=True)
pypsa_network.set_snapshots([datetime.now().strftime("%m/%d/%Y %H:%M:%S")])

pypsa_network.pf()

network = pypsa_network

WARNING:pypsa.io:Warning: Note that when importing from PYPOWER, some PYPOWER features not supported: areas, gencosts, component status
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/19/2023 12:17:32'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.105964 seconds

In [81]:
import pandapower as pp
import pandapower.networks as nw
import pandas as pd
import itertools

net = nw.case39()

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}

In [85]:
pandapower.toolbox.drop_lines(net, [0])

INFO:pandapower.toolbox:dropped 1 lines with 0 line switches

In [95]:
net.liones

,c_nf_per_km,df,from_bus,g_us_per_km,in_service,length_km,max_i_ka,max_loading_percent,name,parallel,r_ohm_per_km,std_type,to_bus,type,x_ohm_per_km
0,1557.117675,1.0,0,0.0,True,1.0,1.004087,100.0,None,1,4.165875,None,1,ol,48.919275
1,1671.444477,1.0,0,0.0,True,1.0,1.673479,100.0,None,1,1.190250,None,38,ol,29.756250
2,573.194026,1.0,1,0.0,True,1.0,0.836740,100.0,None,1,1.547325,None,2,ol,17.972775
3,325.374525,1.0,1,0.0,True,1.0,0.836740,100.0,None,1,8.331750,None,24,ol,10.236150
4,493.410410,1.0,2,0.0,True,1.0,0.836740,100.0,None,1,1.547325,None,3,ol,25.352325
5,476.473106,1.0,2,0.0,True,1.0,0.836740,100.0,None,1,1.309275,None,17,ol,15.830325
6,299.077132,1.0,3,0.0,True,1.0,1.004087,100.0,None,1,0.952200,None,4,ol,15.235200
7,307.991502,1.0,3,0.0,True,1.0,0.836740,100.0,None,1,0.952200,None,13,ol,15.354225
8,96.720920,1.0,4,0.0,True,1.0,2.008175,100.0,None,1,0.238050,None,5,ol,3.094650
9,328.940273,1.0,4,0.0,True,1.0,1.506131,100.0,None,1,0.952200,None,7,ol,13.330800
10,251.830968,1.0,5,0.0,True,1.0,1.506131,100.0,None,1,0.714150,None,6,ol,10.950300
11,309.551517,1.0,5,0.0,True,1.0,0.803270,100.0,None,1,0.833175,None,10,ol,9.760050
12,173.830226,1.0,6,0.0,True,1.0,1.506131,100.0,None,1,0.476100,None,7,ol,5.475150
13,847.756639,1.0,7,0.0,True,1.0,1.506131,100.0,None,1,2.737575,None,8,ol,43.206075
14,2674.311163,1.0,8,0.0,True,1.0,1.506131,100.0,None,1,1.190250,None,38,ol,29.756250
15,162.464403,1.0,9,0.0,True,1.0,1.004087,100.0,None,1,0.476100,None,10,ol,5.118075
16,162.464403,1.0,9,0.0,True,1.0,1.004087,100.0,None,1,0.476100,None,12,ol,5.118075
17,383.986511,1.0,12,0.0,True,1.0,1.004087,100.0,None,1,1.071225,None,13,ol,12.021525
18,815.664905,1.0,13,0.0,True,1.0,1.004087,100.0,None,1,2.142450,None,14,ol,25.828425
19,381.089341,1.0,14,0.0,True,1.0,1.004087,100.0,None,1,1.071225,None,15,ol,11.188350
20,299.077132,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,0.833175,None,16,ol,10.593225
21,677.492161,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,1.904400,None,18,ol,23.209875
22,567.845404,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,0.952200,None,20,ol,16.068375
23,151.544299,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,0.357075,None,23,ol,7.022475
24,293.951369,1.0,16,0.0,True,1.0,1.004087,100.0,None,1,0.833175,None,17,ol,9.760050
25,716.715392,1.0,16,0.0,True,1.0,1.004087,100.0,None,1,1.547325,None,26,ol,20.591325
26,571.634011,1.0,20,0.0,True,1.0,1.506131,100.0,None,1,0.952200,None,21,ol,16.663500
27,411.398201,1.0,21,0.0,True,1.0,1.004087,100.0,None,1,0.714150,None,22,ol,11.426400
28,804.521942,1.0,22,0.0,True,1.0,1.004087,100.0,None,1,2.618550,None,23,ol,41.658750
29,0.000000,1.0,22,0.0,True,1.0,1.506131,100.0,None,1,0.595125,None,35,ol,32.374800
30,1183.382690,1.0,24,0.0,True,1.0,1.004087,100.0,None,1,3.808800,None,25,ol,38.445075
31,533.970796,1.0,25,0.0,True,1.0,1.004087,100.0,None,1,1.666350,None,26,ol,17.496675
32,1738.747975,1.0,25,0.0,True,1.0,1.004087,100.0,None,1,5.118075,None,27,ol,56.417850
33,2293.221822,1.0,25,0.0,True,1.0,1.004087,100.0,None,1,6.784425,None,28,ol,74.390625
34,554.919566,1.0,27,0.0,True,1.0,1.004087,100.0,None,1,1.666350,None,28,ol,17.972775

In [99]:
net = nw.case39()

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}

In [106]:
net.line

,c_nf_per_km,df,from_bus,g_us_per_km,in_service,length_km,max_i_ka,max_loading_percent,name,parallel,r_ohm_per_km,std_type,to_bus,type,x_ohm_per_km
0,1557.117675,1.0,0,0.0,True,1.0,1.004087,100.0,None,1,4.165875,None,1,ol,48.919275
1,1671.444477,1.0,0,0.0,True,1.0,1.673479,100.0,None,1,1.190250,None,38,ol,29.756250
2,573.194026,1.0,1,0.0,True,1.0,0.836740,100.0,None,1,1.547325,None,2,ol,17.972775
3,325.374525,1.0,1,0.0,True,1.0,0.836740,100.0,None,1,8.331750,None,24,ol,10.236150
4,493.410410,1.0,2,0.0,True,1.0,0.836740,100.0,None,1,1.547325,None,3,ol,25.352325
5,476.473106,1.0,2,0.0,True,1.0,0.836740,100.0,None,1,1.309275,None,17,ol,15.830325
6,299.077132,1.0,3,0.0,True,1.0,1.004087,100.0,None,1,0.952200,None,4,ol,15.235200
7,307.991502,1.0,3,0.0,True,1.0,0.836740,100.0,None,1,0.952200,None,13,ol,15.354225
8,96.720920,1.0,4,0.0,True,1.0,2.008175,100.0,None,1,0.238050,None,5,ol,3.094650
9,328.940273,1.0,4,0.0,True,1.0,1.506131,100.0,None,1,0.952200,None,7,ol,13.330800
10,251.830968,1.0,5,0.0,True,1.0,1.506131,100.0,None,1,0.714150,None,6,ol,10.950300
11,309.551517,1.0,5,0.0,True,1.0,0.803270,100.0,None,1,0.833175,None,10,ol,9.760050
12,173.830226,1.0,6,0.0,True,1.0,1.506131,100.0,None,1,0.476100,None,7,ol,5.475150
13,847.756639,1.0,7,0.0,True,1.0,1.506131,100.0,None,1,2.737575,None,8,ol,43.206075
14,2674.311163,1.0,8,0.0,True,1.0,1.506131,100.0,None,1,1.190250,None,38,ol,29.756250
15,162.464403,1.0,9,0.0,True,1.0,1.004087,100.0,None,1,0.476100,None,10,ol,5.118075
16,162.464403,1.0,9,0.0,True,1.0,1.004087,100.0,None,1,0.476100,None,12,ol,5.118075
17,383.986511,1.0,12,0.0,True,1.0,1.004087,100.0,None,1,1.071225,None,13,ol,12.021525
18,815.664905,1.0,13,0.0,True,1.0,1.004087,100.0,None,1,2.142450,None,14,ol,25.828425
19,381.089341,1.0,14,0.0,True,1.0,1.004087,100.0,None,1,1.071225,None,15,ol,11.188350
20,299.077132,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,0.833175,None,16,ol,10.593225
21,677.492161,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,1.904400,None,18,ol,23.209875
22,567.845404,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,0.952200,None,20,ol,16.068375
23,151.544299,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,0.357075,None,23,ol,7.022475
24,293.951369,1.0,16,0.0,True,1.0,1.004087,100.0,None,1,0.833175,None,17,ol,9.760050
25,716.715392,1.0,16,0.0,True,1.0,1.004087,100.0,None,1,1.547325,None,26,ol,20.591325
26,571.634011,1.0,20,0.0,True,1.0,1.506131,100.0,None,1,0.952200,None,21,ol,16.663500
27,411.398201,1.0,21,0.0,True,1.0,1.004087,100.0,None,1,0.714150,None,22,ol,11.426400
28,804.521942,1.0,22,0.0,True,1.0,1.004087,100.0,None,1,2.618550,None,23,ol,41.658750
29,0.000000,1.0,22,0.0,True,1.0,1.506131,100.0,None,1,0.595125,None,35,ol,32.374800
30,1183.382690,1.0,24,0.0,True,1.0,1.004087,100.0,None,1,3.808800,None,25,ol,38.445075
31,533.970796,1.0,25,0.0,True,1.0,1.004087,100.0,None,1,1.666350,None,26,ol,17.496675
32,1738.747975,1.0,25,0.0,True,1.0,1.004087,100.0,None,1,5.118075,None,27,ol,56.417850
33,2293.221822,1.0,25,0.0,True,1.0,1.004087,100.0,None,1,6.784425,None,28,ol,74.390625

In [111]:
import pandapower
import itertools

# Assuming 'net' is your PandaPower network
line_indices = net.line.index.tolist()

# Generate all unique combinations of two lines
n_2_combinations = list(itertools.combinations(line_indices, 2))


for (
    line1,
    line2,
) in range(n_2_combinations):
    print(line1, line2)

TypeError: 'list' object cannot be interpreted as an integer

In [114]:
for elm in range(n_2_combinations):
    elm

TypeError: 'list' object cannot be interpreted as an integer

In [109]:
n_2_combinations

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (0, 10),
 (0, 11),
 (0, 12),
 (0, 13),
 (0, 14),
 (0, 15),
 (0, 16),
 (0, 17),
 (0, 18),
 (0, 19),
 (0, 20),
 (0, 21),
 (0, 22),
 (0, 23),
 (0, 24),
 (0, 25),
 (0, 26),
 (0, 27),
 (0, 28),
 (0, 29),
 (0, 30),
 (0, 31),
 (0, 32),
 (0, 33),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 14),
 (1, 15),
 (1, 16),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 20),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 26),
 (1, 27),
 (1, 28),
 (1, 29),
 (1, 30),
 (1, 31),
 (1, 32),
 (1, 33),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (2, 10),
 (2, 11),
 (2, 12),
 (2, 13),
 (2, 14),
 (2, 15),
 (2, 16),
 (2, 17),
 (2, 18),
 (2, 19),
 (2, 20),
 (2, 21),
 (2, 22),
 (2, 23),
 (2, 24),
 (2, 25),
 (2, 26),
 (2, 27),
 (2, 28),
 (2, 29),
 (2, 30),
 (2, 31),
 (2, 32),
 (2, 33),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (3, 10),
 (3, 11),
 (3, 12),
 (3, 13),
 (3, 14),
 (3, 15),
 (3, 16),
 (3, 17),
 (3, 18),
 (3, 19),
 (3, 20),
 (3, 21),
 (3, 22),
 (3, 23),
 (3, 24),
 (3, 25),
 (3, 26),
 (3, 27),
 (3, 28),
 (3, 29),
 (3, 30),
 (3, 31),
 (3, 32),
 (3, 33),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (4, 10),
 (4, 11),
 (4, 12),
 (4, 13),
 (4, 14),
 (4, 15),
 (4, 16),
 (4, 17),
 (4, 18),
 (4, 19),
 (4, 20),
 (4, 21),
 (4, 22),
 (4, 23),
 (4, 24),
 (4, 25),
 (4, 26),
 (4, 27),
 (4, 28),
 (4, 29),
 (4, 30),
 (4, 31),
 (4, 32),
 (4, 33),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (5, 10),
 (5, 11),
 (5, 12),
 (5, 13),
 (5, 14),
 (5, 15),
 (5, 16),
 (5, 17),
 (5, 18),
 (5, 19),
 (5, 20),
 (5, 21),
 (5, 22),
 (5, 23),
 (5, 24),
 (5, 25),
 (5, 26),
 (5, 27),
 (5, 28),
 (5, 29),
 (5, 30),
 (5, 31),
 (5, 32),
 (5, 33),
 (6, 7),
 (6, 8),
 (6, 9),
 (6, 10),
 (6, 11),
 (6, 12),
 (6, 13),
 (6, 14),
 (6, 15),
 (6, 16),
 (6, 17),
 (6, 18),
 (6, 19),
 (6, 20),
 (6, 21),
 (6, 22),
 (6, 23),
 (6, 24),
 (6, 25),
 (6, 26),
 (6, 27),
 (6, 28),
 (6, 29),
 (6, 30),
 (6, 31),
 (6, 32),
 (6, 33),
 (7, 8),
 (7, 9),
 (7, 10),
 (7, 11),
 (7, 12),
 (7, 13),
 (7, 14),
 (7, 15),
 (7, 16),
 (7, 17),
 (7, 18),
 (7, 19),
 (7, 20),
 (7, 21),
 (7, 22),
 (7, 23),
 (7, 24),
 (7, 25),
 (7, 26),
 (7, 27),
 (7, 28),
 (7, 29),
 (7, 30),
 (7, 31),
 (7, 32),
 (7, 33),
 (8, 9),
 (8, 10),
 (8, 11),
 (8, 12),
 (8, 13),
 (8, 14),
 (8, 15),
 (8, 16),
 (8, 17),
 (8, 18),
 (8, 19),
 (8, 20),
 (8, 21),
 (8, 22),
 (8, 23),
 (8, 24),
 (8, 25),
 (8, 26),
 (8, 27),
 (8, 28),
 (8, 29),
 (8, 30),
 (8, 31),
 (8, 32),
 (8, 33),
 (9, 10),
 (9, 11),
 (9, 12),
 (9, 13),
 (9, 14),
 (9, 15),
 (9, 16),
 (9, 17),
 (9, 18),
 (9, 19),
 (9, 20),
 (9, 21),
 (9, 22),
 (9, 23),
 (9, 24),
 (9, 25),
 (9, 26),
 (9, 27),
 (9, 28),
 (9, 29),
 (9, 30),
 (9, 31),
 (9, 32),
 (9, 33),
 (10, 11),
 (10, 12),
 (10, 13),
 (10, 14),
 (10, 15),
 (10, 16),
 (10, 17),
 (10, 18),
 (10, 19),
 (10, 20),
 (10, 21),
 (10, 22),
 (10, 23),
 (10, 24),
 (10, 25),
 (10, 26),
 (10, 27),
 (10, 28),
 (10, 29),
 (10, 30),
 (10, 31),
 (10, 32),
 (10, 33),
 (11, 12),
 (11, 13),
 (11, 14),
 (11, 15),
 (11, 16),
 (11, 17),
 (11, 18),
 (11, 19),
 (11, 20),
 (11, 21),
 (11, 22),
 (11, 23),
 (11, 24),
 (11, 25),
 (11, 26),
 (11, 27),
 (11, 28),
 (11, 29),
 (11, 30),
 (11, 31),
 (11, 32),
 (11, 33),
 (12, 13),
 (12, 14),
 (12, 15),
 (12, 16),
 (12, 17),
 (12, 18),
 (12, 19),
 (12, 20),
 (12, 21),
 (12, 22),
 (12, 23),
 (12, 24),
 (12, 25),
 (12, 26),
 (12, 27),
 (12, 28),
 (12, 29),
 (12, 30),
 (12, 31),
 (12, 32),
 (12, 33),
 (13, 14),
 (13, 15),
 (13, 16),
 (13, 17),
 (13, 18),
 (13, 19),
 (13, 20),
 (13, 21),
 (13, 22),
 (13, 23),
 (13, 24),
 (13, 25),
 (13, 26),
 (13, 27),
 (13, 28),
 (13, 29),
 (13, 30),
 (13, 31),
 (13, 32),
 (13, 33),
 (14, 15),
 (14, 16),
 (14, 17),
 (14, 18),
 (14, 19),
 (14, 20),
 (14, 21),
 (14, 22),
 (14, 23),
 (14, 24),
 (14, 25),
 (14, 26),
 (14, 27),
 (14, 28),
 (14, 29),
 (14, 30),
 (14, 31),
 (14, 32),
 (14, 33),
 (15, 16),
 (15, 17),
 (15, 18),
 (15, 19),
 (15, 20),
 (15, 21),
 (15, 22),
 (15, 23),
 (15, 24),
 (15, 25),
 (15, 26),
 (15, 27),
 (15, 28),
 (15, 29),
 (15, 30),
 (15, 31),
 (15, 32),
 (15, 33),
 (16, 17),
 (16, 18),
 (16, 19),
 (16, 20),
 (16, 21),
 (16, 22),
 (16, 23),
 (16, 24),
 (16, 25),
 (16, 26),
 (16, 27),
 (16, 28),
 (16, 29),
 (16, 30),
 (16, 31),
 (16, 32),
 (16, 33),
 (17, 18),
 (17, 19),
 (17, 20),
 (17, 21),
 (17, 22),
 (17, 23),
 (17, 24),
 (17, 25),
 (17, 26),
 (17, 27),
 (17, 28),
 (17, 29),
 (17, 30),
 (17, 31),
 (17, 32),
 (17, 33),
 (18, 19),
 (18, 20),
 (18, 21),
 (18, 22),
 (18, 23),
 (18, 24),
 (18, 25),
 (18, 26),
 (18, 27),
 (18, 28),
 (18, 29),
 (18, 30),
 (18, 31),
 (18, 32),
 (18, 33),
 (19, 20),
 (19, 21),
 (19, 22),
 (19, 23),
 (19, 24),
 (19, 25),
 (19, 26),
 (19, 27),
 (19, 28),
 (19, 29),
 (19, 30),
 (19, 31),
 (19, 32),
 (19, 33),
 (20, 21),
 (20, 22),
 (20, 23),
 (20, 24),
 (20, 25),
 (20, 26),
 (20, 27),
 (20, 28),
 (20, 29),
 (20, 30),
 (20, 31),
 (20, 32),
 (20, 33),
 (21, 22),
 (21, 23),
 (21, 24),
 (21, 25),
 (21, 26),
 (21, 27),
 (21, 28),
 (21, 29),
 (21, 30),
 (21, 31),
 (21, 32),
 (21, 33),
 (22, 23),
 (22, 24),
 (22, 25),
 (22, 26),
 (22, 27),
 (22, 28),
 (22, 29),
 (22, 30),
 (22, 31),
 (22, 32),
 (22, 33),
 (23, 24),
 (23, 25),
 (23, 26),
 (23, 27),
 (23, 28),
 (23, 29),
 (23, 30),
 (23, 31),
 (23, 32),
 (23, 33),
 (24, 25),
 (24, 26),
 (24, 27),
 (24, 28),
 (24, 29),
 (24, 30),
 (24, 31),
 (24, 32),
 (24, 33),
 (25, 26),
 (25, 27),
 (25, 28),
 (25, 29),
 (25, 30),
 (25, 31),
 (25, 32),
 (25, 33),
 (26, 27),
 (26, 28),
 (26, 29),
 (26, 30),
 (26, 31),
 (26, 32),
 (26, 33),
 (27, 28),
 (27, 29),
 (27, 30),
 (27, 31),
 (27, 32),
 (27, 33),
 (28, 29),
 (28, 30),
 (28, 31),
 (28, 32),
 (28, 33),
 (29, 30),
 (29, 31),
 (29, 32),
 (29, 33),
 (30, 31),
 (30, 32),
 (30, 33),
 (31, 32),
 (31, 33),
 (32, 33)]

In [107]:
unique_lines

[(0, 1),
 (0, 38),
 (1, 2),
 (1, 24),
 (2, 3),
 (2, 17),
 (3, 4),
 (3, 13),
 (4, 5),
 (4, 7),
 (5, 6),
 (5, 10),
 (6, 7),
 (7, 8),
 (8, 38),
 (9, 10),
 (9, 12),
 (12, 13),
 (13, 14),
 (14, 15),
 (15, 16),
 (15, 18),
 (15, 20),
 (15, 23),
 (16, 17),
 (16, 26),
 (20, 21),
 (21, 22),
 (22, 23),
 (22, 35),
 (24, 25),
 (25, 26),
 (25, 27),
 (25, 28),
 (27, 28)]

In [117]:
import pandapower as pp
import pandapower.networks as nw
import pandas as pd
import itertools


import pandapower
import itertools


# Load the network
net = nw.case39()

# Define new columns for the DataFrame
columns = ["Line 1", "Line 2", "Result", "Iterations"]
contingency_df = pd.DataFrame(columns=columns)


# Assuming 'net' is your PandaPower network
line_indices = net.line.index.tolist()

# Generate all unique combinations of two lines
n_2_combinations = itertools.combinations(line_indices, 2)

# Iterate over each combination
for combo in n_2_combinations:
    line1, line2 = combo  # Unpack the combination

    # Perform your desired operations with line1 and line2
    # For example, you can drop these lines from a copy of the network
    # and perform simulations or analyses
    net = nw.case39()

    pandapower.toolbox.drop_lines(net, [line1, line2])

    try:
        # Run a power flow
        pp.runpp(net, algorithm="nr", max_iteration=100)

        # Check the power flow results
        converged = net.converged
        iterations = net._ppc["iterations"]

    except pp.LoadflowNotConverged:
        # Handle cases where power flow doesn't converge
        converged = False
        iterations = None

    # Append the results to the DataFrame
    contingency_df = contingency_df.append(
        {
            "Line 1": line1,
            "Line 2": line2,
            "Result": converged,  # Use 'converged' to indicate success or failure
            "Iterations": iterations,
        },
        ignore_index=True,
    )

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}
INFO:pandapower.toolbox:dropped 2 lines with 0 line switches

True

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}

KeyboardInterrupt:

In [105]:
contingency_df

   Line 1 Line 2 Result Iterations
0       0    NaN   True          3
1       0    NaN   True          3
2       1    NaN   True          3
3       1    NaN   True          3
4       2    NaN   True          3
5       2    NaN   True          3
6       3    NaN   True          3
7       3    NaN   True          3
8       4    NaN   True          3
9       4    NaN   True          3
10      5    NaN   True          3
11      5    NaN   True          3
12      6    NaN   True          3
13      7    NaN   True          4
14      8    NaN   True          3
15      9    NaN   True          3
16      9    NaN   True          3
17     12    NaN   True          3
18     13    NaN   True          3
19     14    NaN   True          4
20     15    NaN   True          3
21     15    NaN   True          3
22     15    NaN   True          3
23     15    NaN   True          3
24     16    NaN   True          3
25     16    NaN   True          3
26     20    NaN   True          3
27     21    NaN   True          3
28     22    NaN   True          3
29     22    NaN   True          4
30     24    NaN   True          3
31     25    NaN   True          3
32     25    NaN   True          3
33     25    NaN   True          3
34     27    NaN   True          3

In [91]:
unique_lines[0][0]

0

In [1]:
import pandapower as pp
import pandapower.networks as nw
import pandas as pd
import itertools

# Load the network
net = nw.case39()

In [4]:
net.links

AttributeError: 'pandapowerNet' instance has no attribute 'links'

In [ ]:
import pandapower as pp
import pandapower.networks as nw
import pandas as pd
import itertools

# Load the network
net = nw.case39()

# Define new columns for the DataFrame
columns = ["Line 1", "Line 2", "Result", "Iterations"]
contingency_df = pd.DataFrame(columns=columns)

from_bus = net.line.from_bus.to_list()
to_bus = net.line.to_bus.to_list()
unique_lines = list(zip(from_bus, to_bus))

for i in range(len(unique_lines)):
    for j in range(i + 1, len(unique_lines)):
        line1 = unique_lines[i]
        line2 = unique_lines[j]

        # Save original in_service status
        original_status_line1 = net.line.loc[
            (net.line.from_bus == line1[0]) & (net.line.to_bus == line1[1]),
            "in_service",
        ]
        original_status_line2 = net.line.loc[
            (net.line.from_bus == line2[0]) & (net.line.to_bus == line2[1]),
            "in_service",
        ]

        # Outage both lines
        net.line.loc[
            (net.line.from_bus == line1[0]) & (net.line.to_bus == line1[1]),
            "in_service",
        ] = False
        net.line.loc[
            (net.line.from_bus == line2[0]) & (net.line.to_bus == line2[1]),
            "in_service",
        ] = False

        pandapower.toolbox.drop_lines(
            net,
        )

        try:
            # Run a power flow
            pp.runpp(net, algorithm="nr", max_iteration=100)

            # Check the power flow results
            converged = net.converged
            iterations = net._ppc["iterations"]

        except pp.LoadflowNotConverged:
            # Handle cases where power flow doesn't converge
            converged = False
            iterations = None

        # Append the results to the DataFrame
        contingency_df = contingency_df.append(
            {
                "Line 1": line1,
                "Line 2": line2,
                "Result": converged,  # Use 'converged' to indicate success or failure
                "Iterations": iterations,
            },
            ignore_index=True,
        )

        # Restore original in_service status

        net.line.loc[
            (net.line.from_bus == line1[0]) & (net.line.to_bus == line1[1]),
            "in_service",
        ] = original_status_line1
        net.line.loc[
            (net.line.from_bus == line2[0]) & (net.line.to_bus == line2[1]),
            "in_service",
        ] = original_status_line2

INFO:pandapower.convert_format:These dtypes could not be corrected: {'trafo': ['tap_min', 'tap_max']}

In [8]:
network.links

Empty DataFrame
Columns: [bus0, bus1, type, carrier, efficiency, build_year, lifetime, p_nom, p_nom_extendable, p_nom_min, p_nom_max, p_set, p_min_pu, p_max_pu, capital_cost, marginal_cost, length, terrain_factor, ramp_limit_up, ramp_limit_down, p_nom_opt]
Index: []

[0 rows x 21 columns]

In [165]:
# pyPSA n-2
from_bus = network.lines["bus0"].to_list()
to_bus = network.lines["bus1"].to_list()
unique_lines = list(zip(from_bus, to_bus))

# Define new columns for the DataFrame
columns = ["Line 1", "Line 2", "Result", "Iterations"]
contingency_df = pd.DataFrame(columns=columns)

for i in range(len(unique_lines)):
    for j in range(i + 1, len(unique_lines)):

        temp_network = network.copy()

        line1 = unique_lines[i]
        line2 = unique_lines[j]

        # Save original in_service status
        original_status_line1 = network.lines.loc[
            (temp_network.lines["bus0"] == line1[0])
            & (temp_network.lines["bus1"] == line1[1]),
            "status",
        ]
        original_status_line2 = network.lines.loc[
            (temp_network.lines["bus0"] == line2[0])
            & (temp_network.lines["bus1"] == line2[1]),
            "status",
        ]

        # Outage both lines
        temp_network.lines.loc[
            (temp_network.lines["bus0"] == line1[0])
            & (temp_network.lines["bus1"] == line1[1]),
            "status",
        ] = 0.0
        temp_network.lines.loc[
            (temp_network.lines["bus0"] == line2[0])
            & (temp_network.lines["bus1"] == line2[1]),
            "status",
        ] = 0.0

        temp_network.snapshots = [datetime.now().strftime("%m/%d/%Y %H:%M:%S")]

        temp = temp_network.pf(temp_network.snapshots[0])
        result = temp["converged"]["0"].values[0]
        itr = temp["n_iter"]["0"].values[0]
        error = temp["error"]["0"].values[0]

        # Append the results to the DataFrame
        contingency_df = contingency_df.append(
            {
                "Line 1": line1,
                "Line 2": line2,
                "Result": result,  # Use 'converged' to indicate success or failure
                "Iterations": itr,
            },
            ignore_index=True,
        )

        # Outage both lines
        temp_network.lines.loc[
            (temp_network.lines["bus0"] == line1[0])
            & (temp_network.lines["bus1"] == line1[1]),
            "status",
        ] = original_status_line1
        temp_network.lines.loc[
            (temp_network.lines["bus0"] == line2[0])
            & (temp_network.lines["bus1"] == line2[1]),
            "status",
        ] = original_status_line2

INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 16:25:16'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.083971 seconds
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 16:25:17'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.077976 seconds
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 16:25:19'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.080961 seconds
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 16:25:20'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.075258 seconds
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 16:25:21'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.090405 seconds
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 16:25:23'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.080455 seconds
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 16:25:24'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.073976 seconds
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 16:25:26'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.082958 seconds
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 16:25:27'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.079975 seconds

KeyboardInterrupt:

In [4]:
network.snapshots

Index(['12/15/2023 14:47:09'], dtype='object', name='snapshot')

In [161]:
network.lines.loc[
    (network.lines["bus0"] == "1") & (network.lines["bus1"] == "2"), "status"
] = 0.0
network.lines.loc[
    (network.lines["bus0"] == "1") & (network.lines["bus1"] == "2"), "status"
]

Line
L0    0.0
Name: status, dtype: float64

In [167]:
network.sn

In [168]:
network

PyPSA Network
Components:
 - Bus: 39
 - Generator: 10
 - Line: 35
 - Load: 19
 - ShuntImpedance: 2
 - SubNetwork: 1
 - Transformer: 11
Snapshots: 1

In [144]:
len(network.lines)

35

In [145]:
network.lines.status.count()

35

In [152]:
network.lines.status[0]

0.0

In [149]:
network.lines.loc[
    (network.lines["bus0"] == "1") & (network.lines["bus1"] == "2"), "status"
]

Line
L0    0.0
Name: status, dtype: float64

In [129]:
network.lines.status.count()

35

In [133]:
network.lines.status[0]

0.0

In [122]:
temp = network.pf()

INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/14/2023 15:46:33'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.097971 seconds

In [116]:
temp

{'n_iter': SubNetwork           0
 snapshot
 12/14/2023 15:46:33  4,
 'error': SubNetwork                      0
 snapshot
 12/14/2023 15:46:33  2.078536e-09,
 'converged': SubNetwork              0
 snapshot
 12/14/2023 15:46:33  True}

In [119]:
temp = network.pf()
result = temp["converged"]["0"].values[0]
itr = temp["n_iter"]["0"].values[0]
error = temp["error"]["0"].values[0]

True

In [120]:
itr = temp["n_iter"]["0"].values[0]

4

In [95]:
network.lines

,bus0,bus1,r,x,b,s_nom,rateB,rateC,status,v_ang_min,...,num_parallel,sub_network,x_pu,r_pu,g_pu,b_pu,x_pu_eff,r_pu_eff,s_nom_opt,v_nom
Line,,,,,,,,,,,,,,,,,,,,,
L0,1,2,0.000035,0.000411,69.87,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000411,0.000035,0.0,69.87,0.000411,0.000035,0.0,1.0
L1,1,39,0.000010,0.000250,75.00,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000250,0.000010,0.0,75.00,0.000250,0.000010,0.0,1.0
L2,2,3,0.000013,0.000151,25.72,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000151,0.000013,0.0,25.72,0.000151,0.000013,0.0,1.0
L3,2,25,0.000070,0.000086,14.60,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000086,0.000070,0.0,14.60,0.000086,0.000070,0.0,1.0
L4,3,4,0.000013,0.000213,22.14,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000213,0.000013,0.0,22.14,0.000213,0.000013,0.0,1.0
L5,3,18,0.000011,0.000133,21.38,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000133,0.000011,0.0,21.38,0.000133,0.000011,0.0,1.0
L6,4,5,0.000008,0.000128,13.42,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000128,0.000008,0.0,13.42,0.000128,0.000008,0.0,1.0
L7,4,14,0.000008,0.000129,13.82,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000129,0.000008,0.0,13.82,0.000129,0.000008,0.0,1.0
L8,5,6,0.000002,0.000026,4.34,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000026,0.000002,0.0,4.34,0.000026,0.000002,0.0,1.0
L9,5,8,0.000008,0.000112,14.76,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000112,0.000008,0.0,14.76,0.000112,0.000008,0.0,1.0
L10,6,7,0.000006,0.000092,11.30,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000092,0.000006,0.0,11.30,0.000092,0.000006,0.0,1.0
L11,6,11,0.000007,0.000082,13.89,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000082,0.000007,0.0,13.89,0.000082,0.000007,0.0,1.0
L12,7,8,0.000004,0.000046,7.80,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000046,0.000004,0.0,7.80,0.000046,0.000004,0.0,1.0
L13,8,9,0.000023,0.000363,38.04,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000363,0.000023,0.0,38.04,0.000363,0.000023,0.0,1.0
L14,9,39,0.000010,0.000250,120.00,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000250,0.000010,0.0,120.00,0.000250,0.000010,0.0,1.0
L15,10,11,0.000004,0.000043,7.29,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000043,0.000004,0.0,7.29,0.000043,0.000004,0.0,1.0
L16,10,13,0.000004,0.000043,7.29,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000043,0.000004,0.0,7.29,0.000043,0.000004,0.0,1.0
L17,13,14,0.000009,0.000101,17.23,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000101,0.000009,0.0,17.23,0.000101,0.000009,0.0,1.0
L18,14,15,0.000018,0.000217,36.60,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000217,0.000018,0.0,36.60,0.000217,0.000018,0.0,1.0
L19,15,16,0.000009,0.000094,17.10,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000094,0.000009,0.0,17.10,0.000094,0.000009,0.0,1.0
L20,16,17,0.000007,0.000089,13.42,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000089,0.000007,0.0,13.42,0.000089,0.000007,0.0,1.0
L21,16,19,0.000016,0.000195,30.40,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000195,0.000016,0.0,30.40,0.000195,0.000016,0.0,1.0
L22,16,21,0.000008,0.000135,25.48,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000135,0.000008,0.0,25.48,0.000135,0.000008,0.0,1.0
L23,16,24,0.000003,0.000059,6.80,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000059,0.000003,0.0,6.80,0.000059,0.000003,0.0,1.0
L24,17,18,0.000007,0.000082,13.19,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000082,0.000007,0.0,13.19,0.000082,0.000007,0.0,1.0
L25,17,27,0.000013,0.000173,32.16,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000173,0.000013,0.0,32.16,0.000173,0.000013,0.0,1.0
L26,21,22,0.000008,0.000140,25.65,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000140,0.000008,0.0,25.65,0.000140,0.000008,0.0,1.0
L27,22,23,0.000006,0.000096,18.46,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000096,0.000006,0.0,18.46,0.000096,0.000006,0.0,1.0
L28,23,24,0.000022,0.000350,36.10,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000350,0.000022,0.0,36.10,0.000350,0.000022,0.0,1.0
L29,25,26,0.000032,0.000323,51.30,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000323,0.000032,0.0,51.30,0.000323,0.000032,0.0,1.0
L30,26,27,0.000014,0.000147,23.96,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000147,0.000014,0.0,23.96,0.000147,0.000014,0.0,1.0
L31,26,28,0.000043,0.000474,78.02,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000474,0.000043,0.0,78.02,0.000474,0.000043,0.0,1.0
L32,26,29,0.000057,0.000625,102.90,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000625,0.000057,0.0,102.90,0.000625,0.000057,0.0,1.0
L33,28,29,0.000014,0.000151,24.90,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000151,0.000014,0.0,24.90,0.000151,0.000014,0.0,1.0
L34,23,36,0.000005,0.000272,0.00,1.0,0.0,0.0,1.0,-360.0,...,1.0,0,0.000272,0.000005,0.0,0.00,0.000272,0.000005,0.0,1.0

In [102]:
network.lines.iloc[0].bus0

'1'

In [105]:
# Outage both lines
network.lines.loc[
    (network.lines["bus0"] == "1") & (network.lines["bus1"] == "2"), "status"
] = 0

In [49]:
from_bus = net.line.from_bus.to_list()
to_bus = net.line.to_bus.to_list()
unique_lines = list(zip(from_bus, to_bus))
unique_lines

[(0, 1),
 (0, 38),
 (1, 2),
 (1, 24),
 (2, 3),
 (2, 17),
 (3, 4),
 (3, 13),
 (4, 5),
 (4, 7),
 (5, 6),
 (5, 10),
 (6, 7),
 (7, 8),
 (8, 38),
 (9, 10),
 (9, 12),
 (12, 13),
 (13, 14),
 (14, 15),
 (15, 16),
 (15, 18),
 (15, 20),
 (15, 23),
 (16, 17),
 (16, 26),
 (20, 21),
 (21, 22),
 (22, 23),
 (22, 35),
 (24, 25),
 (25, 26),
 (25, 27),
 (25, 28),
 (27, 28)]

In [47]:
line1 = unique_lines[0]
line2 = unique_lines[1]

In [54]:
net.line.loc[
    (net.line.from_bus == line1[0]) & (net.line.to_bus == line1[1]), "in_service"
] = False

In [66]:
contingency_df.loc[contingency_df.Result == False]

     Line 1  Line 2 Result Iterations
270  (4, 7)  (5, 6)  False       None

In [62]:
contingency_df[
    (contingency_df["Line 1"] == (0, 1)) & (contingency_df["Line 2"] == (0, 38))
]

   Line 1   Line 2 Result Iterations
0  (0, 1)  (0, 38)   True          3

In [5]:
import pypsa
import numpy as np

In [6]:
network = pypsa.Network()

In [7]:
n_buses = 3

for i in range(n_buses):
    network.add("Bus", "My bus {}".format(i), v_nom=20.0)

network.buses

attribute,v_nom,type,x,y,carrier,unit,v_mag_pu_set,v_mag_pu_min,v_mag_pu_max,control,sub_network
Bus,,,,,,,,,,,
My bus 0,20.0,,0.0,0.0,AC,None,1.0,0.0,inf,PQ,
My bus 1,20.0,,0.0,0.0,AC,None,1.0,0.0,inf,PQ,
My bus 2,20.0,,0.0,0.0,AC,None,1.0,0.0,inf,PQ,

In [8]:
for i in range(n_buses):
    network.add(
        "Line",
        "My line {}".format(i),
        bus0="My bus {}".format(i),
        bus1="My bus {}".format((i + 1) % n_buses),
        x=0.1,
        r=0.01,
    )

network.lines

attribute,bus0,bus1,type,x,r,g,b,s_nom,s_nom_extendable,s_nom_min,...,v_ang_min,v_ang_max,sub_network,x_pu,r_pu,g_pu,b_pu,x_pu_eff,r_pu_eff,s_nom_opt
Line,,,,,,,,,,,,,,,,,,,,,
My line 0,My bus 0,My bus 1,,0.1,0.01,0.0,0.0,0.0,False,0.0,...,-inf,inf,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
My line 1,My bus 1,My bus 2,,0.1,0.01,0.0,0.0,0.0,False,0.0,...,-inf,inf,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
My line 2,My bus 2,My bus 0,,0.1,0.01,0.0,0.0,0.0,False,0.0,...,-inf,inf,,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
network.add("Generator", "My gen", bus="My bus 0", p_set=100, control="PQ")

network.generators

attribute,bus,control,type,p_nom,p_nom_extendable,p_nom_min,p_nom_max,p_min_pu,p_max_pu,p_set,...,shut_down_cost,min_up_time,min_down_time,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,p_nom_opt
Generator,,,,,,,,,,,,,,,,,,,,,
My gen,My bus 0,PQ,,0.0,False,0.0,inf,0.0,1.0,100.0,...,0.0,0,0,1,0,NaN,NaN,1.0,1.0,0.0

In [10]:
network.generators.p_set

Generator
My gen    100.0
Name: p_set, dtype: float64

In [11]:
network.add("Load", "My load", bus="My bus 1", p_set=100)

network.loads

attribute       bus carrier type  p_set  q_set  sign
Load
My load    My bus 1               100.0    0.0  -1.0

In [12]:
network.loads.p_set

Load
My load    100.0
Name: p_set, dtype: float64

In [27]:
network.loads.q_set = 100.0

In [41]:
network

PyPSA Network
Components:
 - Bus: 39
 - Generator: 10
 - Line: 35
 - Load: 19
 - ShuntImpedance: 2
 - SubNetwork: 1
 - Transformer: 11
Snapshots: 1

In [42]:
network.pf()

INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/15/2023 15:00:29'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.052982 seconds

{'n_iter': SubNetwork           0
 snapshot
 12/15/2023 15:00:29  4,
 'error': SubNetwork                      0
 snapshot
 12/15/2023 15:00:29  2.078423e-09,
 'converged': SubNetwork              0
 snapshot
 12/15/2023 15:00:29  True}

In [57]:
network.lines.iloc[0].status == 0

False

In [64]:
network.lines

,bus0,bus1,r,x,b,s_nom,rateB,rateC,status,v_ang_min,...,num_parallel,sub_network,x_pu,r_pu,g_pu,b_pu,x_pu_eff,r_pu_eff,s_nom_opt,v_nom
Line,,,,,,,,,,,,,,,,,,,,,
L0,1,2,0.000035,0.000411,69.87,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000411,0.000035,0.0,69.87,0.000411,0.000035,0.0,1.0
L1,1,39,0.000010,0.000250,75.00,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000250,0.000010,0.0,75.00,0.000250,0.000010,0.0,1.0
L2,2,3,0.000013,0.000151,25.72,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000151,0.000013,0.0,25.72,0.000151,0.000013,0.0,1.0
L3,2,25,0.000070,0.000086,14.60,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000086,0.000070,0.0,14.60,0.000086,0.000070,0.0,1.0
L4,3,4,0.000013,0.000213,22.14,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000213,0.000013,0.0,22.14,0.000213,0.000013,0.0,1.0
L5,3,18,0.000011,0.000133,21.38,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000133,0.000011,0.0,21.38,0.000133,0.000011,0.0,1.0
L6,4,5,0.000008,0.000128,13.42,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000128,0.000008,0.0,13.42,0.000128,0.000008,0.0,1.0
L7,4,14,0.000008,0.000129,13.82,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000129,0.000008,0.0,13.82,0.000129,0.000008,0.0,1.0
L8,5,6,0.000002,0.000026,4.34,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000026,0.000002,0.0,4.34,0.000026,0.000002,0.0,1.0
L9,5,8,0.000008,0.000112,14.76,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000112,0.000008,0.0,14.76,0.000112,0.000008,0.0,1.0
L10,6,7,0.000006,0.000092,11.30,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000092,0.000006,0.0,11.30,0.000092,0.000006,0.0,1.0
L11,6,11,0.000007,0.000082,13.89,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000082,0.000007,0.0,13.89,0.000082,0.000007,0.0,1.0
L12,7,8,0.000004,0.000046,7.80,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000046,0.000004,0.0,7.80,0.000046,0.000004,0.0,1.0
L13,8,9,0.000023,0.000363,38.04,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000363,0.000023,0.0,38.04,0.000363,0.000023,0.0,1.0
L14,9,39,0.000010,0.000250,120.00,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000250,0.000010,0.0,120.00,0.000250,0.000010,0.0,1.0
L15,10,11,0.000004,0.000043,7.29,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000043,0.000004,0.0,7.29,0.000043,0.000004,0.0,1.0
L16,10,13,0.000004,0.000043,7.29,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000043,0.000004,0.0,7.29,0.000043,0.000004,0.0,1.0
L17,13,14,0.000009,0.000101,17.23,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000101,0.000009,0.0,17.23,0.000101,0.000009,0.0,1.0
L18,14,15,0.000018,0.000217,36.60,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000217,0.000018,0.0,36.60,0.000217,0.000018,0.0,1.0
L19,15,16,0.000009,0.000094,17.10,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000094,0.000009,0.0,17.10,0.000094,0.000009,0.0,1.0
L20,16,17,0.000007,0.000089,13.42,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000089,0.000007,0.0,13.42,0.000089,0.000007,0.0,1.0
L21,16,19,0.000016,0.000195,30.40,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000195,0.000016,0.0,30.40,0.000195,0.000016,0.0,1.0
L22,16,21,0.000008,0.000135,25.48,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000135,0.000008,0.0,25.48,0.000135,0.000008,0.0,1.0
L23,16,24,0.000003,0.000059,6.80,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000059,0.000003,0.0,6.80,0.000059,0.000003,0.0,1.0
L24,17,18,0.000007,0.000082,13.19,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000082,0.000007,0.0,13.19,0.000082,0.000007,0.0,1.0
L25,17,27,0.000013,0.000173,32.16,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000173,0.000013,0.0,32.16,0.000173,0.000013,0.0,1.0
L26,21,22,0.000008,0.000140,25.65,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000140,0.000008,0.0,25.65,0.000140,0.000008,0.0,1.0
L27,22,23,0.000006,0.000096,18.46,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000096,0.000006,0.0,18.46,0.000096,0.000006,0.0,1.0
L28,23,24,0.000022,0.000350,36.10,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000350,0.000022,0.0,36.10,0.000350,0.000022,0.0,1.0
L29,25,26,0.000032,0.000323,51.30,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000323,0.000032,0.0,51.30,0.000323,0.000032,0.0,1.0
L30,26,27,0.000014,0.000147,23.96,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000147,0.000014,0.0,23.96,0.000147,0.000014,0.0,1.0
L31,26,28,0.000043,0.000474,78.02,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000474,0.000043,0.0,78.02,0.000474,0.000043,0.0,1.0
L32,26,29,0.000057,0.000625,102.90,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000625,0.000057,0.0,102.90,0.000625,0.000057,0.0,1.0
L33,28,29,0.000014,0.000151,24.90,1.0,0.0,1.0,1.0,-360.0,...,1.0,0,0.000151,0.000014,0.0,24.90,0.000151,0.000014,0.0,1.0
L34,23,36,0.000005,0.000272,0.00,1.0,0.0,0.0,1.0,-360.0,...,1.0,0,0.000272,0.000005,0.0,0.00,0.000272,0.000005,0.0,1.0

In [69]:
network.lines.loc[
    (network.lines["bus0"] == "1") & (network.lines["bus1"] == "2"), "status"
]

Line
L0    0.0
Name: status, dtype: float64

In [75]:
network.lines.status = 0.0

In [79]:
network.lines.status

Line
L0     0.0
L1     0.0
L2     0.0
L3     0.0
L4     0.0
L5     0.0
L6     0.0
L7     0.0
L8     0.0
L9     0.0
L10    0.0
L11    0.0
L12    0.0
L13    0.0
L14    0.0
L15    0.0
L16    0.0
L17    0.0
L18    0.0
L19    0.0
L20    0.0
L21    0.0
L22    0.0
L23    0.0
L24    0.0
L25    0.0
L26    0.0
L27    0.0
L28    0.0
L29    0.0
L30    0.0
L31    0.0
L32    0.0
L33    0.0
L34    0.0
Name: status, dtype: float64

In [76]:
network.pf()

INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['12/15/2023 15:00:29'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.062980 seconds

{'n_iter': SubNetwork           0
 snapshot
 12/15/2023 15:00:29  4,
 'error': SubNetwork                      0
 snapshot
 12/15/2023 15:00:29  2.078423e-09,
 'converged': SubNetwork              0
 snapshot
 12/15/2023 15:00:29  True}

In [58]:
network.lines.iloc[0].status

1.0

In [ ]:
network.lines.loc[
    (network.lines.from_bus == line1[0]) & (net.line.to_bus == line1[1]), "in_service"
] = False

In [46]:
network.lines_t.p0

,L0,L1,L2,L3,L4,L5,L6,L7,L8,L9,...,L25,L26,L27,L28,L29,L30,L31,L32,L33,L34
snapshot,,,,,,,,,,,,,,,,,,,,,
12/15/2023 15:00:29,-121.096028,121.096028,364.305679,-235.86942,83.606861,-42.94271,-149.70646,-266.870935,-468.387463,318.498956,...,15.762179,-590.406669,56.951944,340.994025,74.355227,266.212581,-140.808317,-190.209503,-347.5964,-558.573239

In [47]:
network.buses_t.v_ang * 180 / np.pi

Bus,1,2,3,4,5,6,7,8,9,10,...,30,31,32,33,34,35,36,37,38,39
snapshot,,,,,,,,,,,,,,,,,,,,,
12/15/2023 15:00:29,-8.368513,-5.771915,-8.608104,-9.512179,-8.432428,-7.733848,-9.907067,-10.402832,-10.165247,-5.30599,...,-3.359887,0.0,2.658,3.995414,2.981283,5.208169,7.821122,2.393336,7.71561,-9.93535

In [48]:
network.buses_t.v_mag_pu

Bus,1,2,3,4,5,6,7,8,9,10,...,30,31,32,33,34,35,36,37,38,39
snapshot,,,,,,,,,,,,,,,,,,,,,
12/15/2023 15:00:29,1.048516,1.051598,1.036419,1.016848,1.013999,1.0109,1.001945,1.001797,1.030602,1.021327,...,1.048,0.982,0.983,0.997,1.012,1.049,1.064,1.028,1.027,1.03

In [49]:
network

PyPSA Network
Components:
 - Bus: 39
 - Generator: 10
 - Line: 35
 - Load: 19
 - ShuntImpedance: 2
 - SubNetwork: 1
 - Transformer: 11
Snapshots: 1